apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ssasd22445 
  janus-idp.io/tekton: ssasd22445
  backstage.io/kubernetes-id: ssasd22445
  backstage.io/kubernetes-namespace: ssasd22445 
  app.kubernetes.io/part-of: ssasd22445
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  