apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ssasd22445
  janus-idp.io/tekton: ssasd22445
  backstage.io/kubernetes-id: ssasd22445
  backstage.io/kubernetes-namespace: ssasd22445 
  app.kubernetes.io/part-of: ssasd22445
resources: 
- deployment.yaml
- route.yaml
- service.yaml
